from fasthtml.common import A, Card, Div, Li, Ul
from fasthtml.svg import Defs, ClipPath, Rect, G, Path, Text, Tspan, Svg, Desc

from blocks import block

id = "BuildingPermits"


def bld_permits_block(rt):

    path = "/building_permits"

    @rt(path)
    def get():
        return BuildingPermits()

    return block(path, id, "Building Permits")


def BuildingPermits():

    url1 = "https://www.census.gov/construction/nrc/pdf/newresconst.pdf"
    url2 = "https://tradingeconomics.com/united-states/building-permits"

    card = Card(
        cls="wlv-details",
        footer=Ul(
            Li(A(url1, href=url1, target="_blank")),
            Li(A(url2, href=url2, target="_blank")),
        ),
    )
    return Div(
        card,
        svg_chart2,
        id=id,
    )


# https://h2f.answer.ai/
svg_chart2 = Svg(
    Desc("Created with Highcharts 10.1.0"),
    Defs(
        ClipPath(
            Rect(x="0", y="0", width="521", height="295", fill="none"),
            id="highcharts-8mpt8p1-57-",
        ),
        ClipPath(
            Rect(x="0", y="0", width="521", height="295", fill="none"),
            id="highcharts-8mpt8p1-74-",
        ),
        ClipPath(
            Rect(x="25", y="40", width="521", height="295", fill="none"),
            id="highcharts-8mpt8p1-75-",
        ),
    ),
    Rect(
        fill="#ffffff",
        x="0",
        y="0",
        width="600",
        height="410",
        rx="0",
        ry="0",
        cls="highcharts-background",
    ),
    Rect(
        fill="none",
        x="25",
        y="40",
        width="521",
        height="295",
        cls="highcharts-plot-background",
    ),
    G(
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 73.5 40 L 73.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 138.5 40 L 138.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 203.5 40 L 203.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 268.5 40 L 268.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 333.5 40 L 333.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 398.5 40 L 398.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 464.5 40 L 464.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 529.5 40 L 529.5 335",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        data_z_index="1",
        cls="highcharts-grid highcharts-xaxis-grid",
    ),
    G(
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 25 335.5 L 546 335.5",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 25 291.5 L 546 291.5",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 25 240.5 L 546 240.5",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 25 189.5 L 546 189.5",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 25 138.5 L 546 138.5",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 25 87.5 L 546 87.5",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="1",
            stroke_dasharray="1,1",
            data_z_index="1",
            d="M 25 39.5 L 546 39.5",
            opacity="1",
            cls="highcharts-grid-line",
        ),
        data_z_index="1",
        cls="highcharts-grid highcharts-yaxis-grid",
    ),
    Rect(
        fill="none",
        data_z_index="1",
        x="25",
        y="40",
        width="521",
        height="295",
        cls="highcharts-plot-border",
    ),
    G(data_z_index="1", cls="highcharts-grid highcharts-yaxis-grid"),
    G(
        Path(
            fill="none",
            stroke="#E6E6E6",
            stroke_width="1",
            data_z_index="7",
            d="M 25 335.5 L 546 335.5",
            cls="highcharts-axis-line",
        ),
        data_z_index="2",
        cls="highcharts-axis highcharts-xaxis",
    ),
    G(
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="0.5",
            d="M 546 335.25 L 556 335.25",
            opacity="1",
            cls="highcharts-tick",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="0.5",
            d="M 546 291.25 L 556 291.25",
            opacity="1",
            cls="highcharts-tick",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="0.5",
            d="M 546 240.25 L 556 240.25",
            opacity="1",
            cls="highcharts-tick",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="0.5",
            d="M 546 189.25 L 556 189.25",
            opacity="1",
            cls="highcharts-tick",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="0.5",
            d="M 546 138.25 L 556 138.25",
            opacity="1",
            cls="highcharts-tick",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="0.5",
            d="M 546 87.25 L 556 87.25",
            opacity="1",
            cls="highcharts-tick",
        ),
        Path(
            fill="none",
            stroke="#E7E7E7",
            stroke_width="0.5",
            d="M 546 39.75 L 556 39.75",
            opacity="1",
            cls="highcharts-tick",
        ),
        Path(
            fill="none",
            stroke="#E6E6E6",
            stroke_width="1",
            data_z_index="7",
            d="M 546.5 40 L 546.5 335",
            cls="highcharts-axis-line",
        ),
        data_z_index="2",
        cls="highcharts-axis highcharts-yaxis",
    ),
    G(
        Path(
            fill="none",
            stroke="#E6E6E6",
            stroke_width="1",
            data_z_index="7",
            d="M 24.5 40 L 24.5 335",
            cls="highcharts-axis-line",
        ),
        data_z_index="2",
        cls="highcharts-axis highcharts-yaxis",
    ),
    G(
        G(
            Rect(
                x="4",
                y="179",
                width="26",
                height="117",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="36",
                y="195",
                width="26",
                height="101",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="69",
                y="155",
                width="26",
                height="141",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="101",
                y="212",
                width="26",
                height="84",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="134",
                y="245",
                width="26",
                height="51",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="166",
                y="275",
                width="26",
                height="21",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="199",
                y="235",
                width="26",
                height="61",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="232",
                y="270",
                width="26",
                height="26",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="264",
                y="223",
                width="26",
                height="73",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="297",
                y="256",
                width="26",
                height="40",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="329",
                y="260",
                width="26",
                height="36",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="362",
                y="206",
                width="26",
                height="90",
                fill="#4f81bd",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="394",
                y="143",
                width="26",
                height="153",
                fill="rgb(205,205,205)",
                fill_opacity="1",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="427",
                y="77",
                width="26",
                height="219",
                fill="rgb(205,205,205)",
                fill_opacity="1",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="459",
                y="56",
                width="26",
                height="240",
                fill="rgb(205,205,205)",
                fill_opacity="1",
                opacity="1",
                cls="highcharts-point",
            ),
            Rect(
                x="492",
                y="19",
                width="26",
                height="277",
                fill="rgb(205,205,205)",
                fill_opacity="1",
                opacity="1",
                cls="highcharts-point",
            ),
            data_z_index="4",
            opacity="1",
            transform="translate(25,40) scale(1 1)",
            clip_path="url(#highcharts-8mpt8p1-74-)",
            cls="highcharts-series highcharts-series-0 highcharts-column-series",
        ),
        G(
            data_z_index="4",
            opacity="1",
            transform="translate(25,40) scale(1 1)",
            clip_path="none",
            cls="highcharts-markers highcharts-series-0 highcharts-column-series",
        ),
        data_z_index="3",
        cls="highcharts-series-group",
    ),
    Text(
        "US Building Permits",
        Tspan("- Thousand", style="font-size: 10px;"),
        x="24",
        text_anchor="start",
        data_z_index="4",
        style="color: rgb(51, 51, 51); font-size: 1em; fill: rgb(51, 51, 51); font-family: Helvetica;",
        y="20",
        cls="highcharts-title",
    ),
    Text(
        "Source: tradingeconomics.com | U.S. Census Bureau",
        x="590",
        text_anchor="end",
        data_z_index="4",
        style="color: rgb(51, 51, 51); fill: rgb(51, 51, 51); font-size: 0.8em; font-family: Helvetica;",
        y="402",
        cls="highcharts-subtitle",
    ),
    Text(
        x="10",
        text_anchor="start",
        data_z_index="4",
        style="color: rgb(102, 102, 102); fill: rgb(102, 102, 102);",
        y="407",
        cls="highcharts-caption",
    ),
    G(
        Text(
            "2024",
            x="73.84375",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        Text(
            "Mar",
            x="138.96875",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        Text(
            "May",
            x="204.09375",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        Text(
            "Jul",
            x="269.21875",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        Text(
            "Sep",
            x="334.34375",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        Text(
            "Nov",
            x="399.46875",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        Text(
            "Mar",
            x="464.59375",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        Text(
            "Sep",
            x="529.71875",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="middle",
            transform="translate(0,0)",
            y="350",
            opacity="1",
        ),
        data_z_index="7",
        cls="highcharts-axis-labels highcharts-xaxis-labels",
    ),
    G(
        Text(
            Tspan("1.37K", cls="yLabels_"),
            x="0",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="start",
            transform="translate(0,0)",
            visibility="hidden",
        ),
        Text(
            Tspan("1.43K", cls="yLabels_"),
            x="551",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="start",
            transform="translate(0,0)",
            y="294",
            opacity="1",
        ),
        Text(
            Tspan("1.5K", cls="yLabels_"),
            x="551",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="start",
            transform="translate(0,0)",
            y="243",
            opacity="1",
        ),
        Text(
            Tspan("1.57K", cls="yLabels_"),
            x="551",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="start",
            transform="translate(0,0)",
            y="192",
            opacity="1",
        ),
        Text(
            Tspan("1.64K", cls="yLabels_"),
            x="551",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="start",
            transform="translate(0,0)",
            y="141",
            opacity="1",
        ),
        Text(
            Tspan("1.71K", cls="yLabels_"),
            x="551",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="start",
            transform="translate(0,0)",
            y="90",
            opacity="1",
        ),
        Text(
            Tspan("1.77K", cls="yLabels_"),
            x="0",
            style="color: rgb(51, 51, 51); cursor: default; font-size: 1em; font-family: Helvetica; fill: rgb(51, 51, 51);",
            text_anchor="start",
            transform="translate(0,0)",
            visibility="hidden",
        ),
        data_z_index="7",
        cls="highcharts-axis-labels highcharts-yaxis-labels",
    ),
    G(data_z_index="7", cls="highcharts-axis-labels highcharts-yaxis-labels"),
    G(
        data_z_index="99",
        clip_path="url(#highcharts-8mpt8p1-75-)",
        cls="highcharts-control-points",
    ),
    **{"xmlns:xlink": "http://www.w3.org/1999/xlink"},
    version="1.1",
    style='font-family: "Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif; font-size: 12px;',
    xmlns="http://www.w3.org/2000/svg",
    width="600",
    height="410",
    viewbox="0 0 600 410",
    cls="highcharts-root"
)
